use_frameworks!

target 'MGRSMapKit_Example' do
  pod 'MGRSMapKit', :path => '../'

  target 'MGRSMapKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
